"""Leakage / protection guard tests — adversarial split markers (T1..T13).

Real assertions against clouda_contracts.protection (the module the
quality gate must consume, fail-closed) plus importorskip stubs for the
pending clouda_data.quality.leakage module.
"""

from __future__ import annotations

from typing import Any

import pytest

leakage = pytest.importorskip("clouda_data.quality.leakage")

from clouda_contracts.protection import (  # noqa: E402
    is_training_split_eligible,
    record_is_protected,
    string_marks_protected,
)

from tests.quality.conftest import make_row  # noqa: E402


class TestAdversarialSplitMarkers:
    def test_holdout_casing_is_protected(self) -> None:
        assert string_marks_protected("Holdout") is True

    def test_holdout_whitespace_is_protected(self) -> None:
        assert string_marks_protected(" holdout ") is True

    def test_train_plus_holdout_is_protected(self) -> None:
        assert string_marks_protected("train+holdout") is True

    def test_benchmark_holdout_v2_is_protected(self) -> None:
        assert string_marks_protected("benchmark_holdout_v2") is True

    def test_plain_train_is_not_protected_marker(self) -> None:
        assert string_marks_protected("train") is False

    def test_holdout_not_training_eligible(self) -> None:
        assert is_training_split_eligible("holdout") is False


class TestProtectionRecords:
    def test_protected_int_flag_is_protected(self) -> None:
        row = make_row("smp_p", target_split="train").to_dict()
        row["provenance"] = {"protected": 1}
        assert record_is_protected(row) is True

    def test_provenance_as_list_is_protected(self) -> None:
        row = make_row("smp_l", target_split="train").to_dict()
        row["provenance"] = ["holdout"]
        assert record_is_protected(row) is True

    def test_nested_provenance_source_split_is_protected(self) -> None:
        row = make_row("smp_n", target_split="train").to_dict()
        row["provenance"] = {"origin": {"source_split": "holdout"}}
        assert record_is_protected(row) is True

    def test_role_train_target_holdout_is_protected(self) -> None:
        row = make_row("smp_r", target_split="holdout").to_dict()
        row["role"] = "train"
        assert record_is_protected(row) is True

    def test_clean_train_row_is_not_protected(self) -> None:
        row = make_row("smp_t", target_split="train").to_dict()
        assert record_is_protected(row) is False


class TestLeakageModule:
    def test_effective_partition_uses_canonical_split_policy(self) -> None:
        assert (
            leakage.effective_partition(make_row("smp_t", target_split="train"))
            == "TRAIN"
        )
        assert (
            leakage.effective_partition(make_row("smp_h", target_split="holdout"))
            == "PROTECTED"
        )


class TestUnassignedValueScan:
    """The rule-5 provenance/metadata value scan must catch markers that are
    *encoded as* values, not free text that merely *mentions* one."""

    @staticmethod
    def _unassigned_row(sample_id: str, **overrides: Any) -> Any:
        row = make_row(sample_id, **overrides)
        assert row.target_split.value == "unassigned"
        return row

    def test_benign_benchmark_uri_stays_unpartitioned(self) -> None:
        row = self._unassigned_row(
            "smp_uri",
            provenance={"source_uri": "benchmarks/ocr_arabic/benchmark_manifest.jsonl"},
        )
        assert leakage.effective_partition(row) == "UNPARTITIONED"

    def test_benign_notes_stay_unpartitioned(self) -> None:
        row = self._unassigned_row(
            "smp_note",
            provenance={"note": "generated by the benchmark factory"},
        )
        assert leakage.effective_partition(row) == "UNPARTITIONED"

    def test_no_critical_from_benign_uri_shared_document(self) -> None:
        train_row = make_row("smp_tr", document_id="docA", target_split="train")
        uri_row = self._unassigned_row(
            "smp_ur2",
            document_id="docA",
            provenance={"source_uri": "benchmarks/ocr/benchmark.jsonl"},
        )
        report = leakage.detect_leakage([train_row, uri_row])
        assert report.passed is True

    def test_obfuscated_marker_under_noncanonical_key_is_protected(self) -> None:
        # cyrillic 'о' inside "holdout" under a non-canonical key (R2-H1)
        row = self._unassigned_row(
            "smp_h1",
            provenance={"data_split": "hоldout"},
        )
        assert leakage.effective_partition(row) == "PROTECTED"

    def test_exact_marker_value_under_free_text_key_is_protected(self) -> None:
        row = self._unassigned_row(
            "smp_mark",
            provenance={"reviewer_note": "protected"},
        )
        assert leakage.effective_partition(row) == "PROTECTED"

    def test_separator_obfuscated_marker_value_is_protected(self) -> None:
        row = self._unassigned_row(
            "smp_sep",
            provenance={"tag": "evaluation.only"},
        )
        assert leakage.effective_partition(row) == "PROTECTED"
