from enum import Enum


class TeacherPipelineMode(str, Enum):
    DISABLED = "disabled"
    MOCK = "mock"
    LIVE = "live"


class DispatchMode(str, Enum):
    DISABLED = "disabled"
    MOCK = "mock"
    LIVE = "live"


class TeacherRole(str, Enum):
    PAGE_ANALYSIS = "PAGE_ANALYSIS"
    ARABIC_MAIN_OCR = "ARABIC_MAIN_OCR"
    MARGIN_AND_FOOTNOTE_OCR = "MARGIN_AND_FOOTNOTE_OCR"
    ENGLISH_OCR = "ENGLISH_OCR"
    IMAGE_GROUNDED_ARABIC_CORRECTION = "IMAGE_GROUNDED_ARABIC_CORRECTION"
    STRUCTURE_RECONSTRUCTION = "STRUCTURE_RECONSTRUCTION"
    QUALITY_JUDGE = "QUALITY_JUDGE"
    DIFFICULT_PAGE_VISION = "DIFFICULT_PAGE_VISION"
    FINAL_IMAGE_GROUNDED_REVIEW = "FINAL_IMAGE_GROUNDED_REVIEW"
    SUBJECT_CLASSIFICATION = "SUBJECT_CLASSIFICATION"


class DatasetDecision(str, Enum):
    GOLD = "GOLD"
    SILVER = "SILVER"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    HOLDOUT = "HOLDOUT"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    BLOCKED = "BLOCKED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
