"""Packing integration boundary for HunyuanOCR-1.5.

Mode A (default, offline): validate raw export + produce a packing PLAN and
the exact env/config artifacts the official upstream packer needs. No model,
no tokenizer, no network.

Mode B (explicit only): delegate to the user's local HunyuanOCR checkout.
Never auto-downloads weights, never auto-clones, never runs the official
packer unless explicitly configured.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from clouda_training.hunyuan.models import (
    DEFAULT_PACK_LENGTH,
    HUNYUAN_COMPAT_REPOSITORY,
    HUNYUAN_COMPAT_REVISION,
)
from clouda_training.hunyuan.validators import validate_raw_jsonl


@dataclass
class PackingPlan:
    """Everything the official upstream packer needs, without running it."""

    raw_jsonl_path: str
    pack_length: int = DEFAULT_PACK_LENGTH
    input_list_path: str = ""
    env_overrides: dict[str, str] = field(default_factory=dict)
    upstream_command: str = ""
    upstream_repository: str = HUNYUAN_COMPAT_REPOSITORY
    upstream_revision: str = HUNYUAN_COMPAT_REVISION
    raw_validation: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class UpstreamPaths:
    """Operator-supplied local paths for Mode B. Never inferred, never fetched."""

    source_dir: str  # local HunyuanOCR checkout
    model_dir: str  # local HunyuanOCR weights directory


def build_packing_plan(
    raw_jsonl_path: str | Path,
    *,
    pack_length: int = DEFAULT_PACK_LENGTH,
    output_dir: str | Path | None = None,
    check_image_exists: bool = False,
) -> PackingPlan:
    """Mode A: validate raw export and emit an upstream-compatible packing plan."""
    raw_path = Path(raw_jsonl_path)
    validation = validate_raw_jsonl(raw_path, check_image_exists=check_image_exists)
    out_dir = Path(output_dir) if output_dir else raw_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    input_list = out_dir / "data_list.txt"
    input_list.write_text(
        f"# Generated by Clouda Hunyuan bridge — paths for upstream pack_data.sh\n"
        f"{raw_path.resolve()}\n",
        encoding="utf-8",
        newline="\n",
    )
    env = {
        "INPUT_LIST": str(input_list.resolve()),
        "PACK_OUTPUT": str((out_dir / f"parsing_packed_{pack_length}.jsonl").resolve()),
        "PACK_LEN": str(pack_length),
    }
    command = (
        "MODEL_PATH=<local HunyuanOCR model dir> "
        + " ".join(f"{k}={v}" for k, v in env.items())
        + " bash scripts/pack_data.sh"
    )
    plan = PackingPlan(
        raw_jsonl_path=str(raw_path),
        pack_length=pack_length,
        input_list_path=str(input_list),
        env_overrides=env,
        upstream_command=command,
        raw_validation=validation,
    )
    plan_path = out_dir / "packing_plan.json"
    plan_path.write_text(
        json.dumps(plan.to_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
        newline="\n",
    )
    return plan


def verify_local_upstream(paths: UpstreamPaths) -> dict[str, Any]:
    """Validate operator-supplied Mode B paths WITHOUT executing anything."""
    source = Path(paths.source_dir)
    model = Path(paths.model_dir)
    report: dict[str, Any] = {"source_dir": str(source), "model_dir": str(model)}
    expected_source_files = (
        "scripts/pack_data.sh",
        "tools/pipeline_count_and_pack.py",
        "train/train_hunyuan.py",
    )
    missing_source = [f for f in expected_source_files if not (source / f).is_file()]
    report["source_ok"] = source.is_dir() and not missing_source
    report["missing_source_files"] = missing_source
    expected_model_files = ("config.json",)
    missing_model = [f for f in expected_model_files if not (model / f).is_file()]
    report["model_ok"] = model.is_dir() and not missing_model
    report["missing_model_files"] = missing_model
    return report
